[metadata]
name = "Tropical Paradise Dark"
author = "Sherman Rofeman (https://github.com/skippyr)"
license = "MIT"
origin_url = "https://github.com/skippyr/tropical_paradise"

[colors]

# Basic Colors
background = "#140000" # Dark Black
foreground = "#fdebab" # Light White
cursor_bg = "#ff0d00" # Dark Red
cursor_border = "#ff0d00" # Dark Red
cursor_fg = "#140000" # Dark Black
selection_bg = "#fdebab" # Light White
selection_fg = "#140000" # Dark Black


# Dark Colors
ansi = [
    "#140000", # Dark Black
    "#ff0d00", # Dark Red
    "#77bc00", # Dark Green
    "#ffae00", # Dark Yellow
    "#4eb7cc", # Dark Blue
    "#ff5bdb", # Dark Magenta
    "#02d5b5", # Dark Cyan
    "#beb79c", # Dark White
]

# Bright Colors
brights = [
    "#978f63", # Light Black
    "#f57f79", # Light Red
    "#d4f0a5", # Light Green
    "#fcd276", # Light Yellow
    "#93ccd9", # Light Blue
    "#ffd5f6", # Light Magenta
    "#87e2c5", # Light Cyan
    "#fdebab", # Light White
]
